#pragma once
#define BG_WIDTH 330
#define BG_HEIGHT 600
//Ç½
#define WALL_WIDTH 30
#define WALL_HEIGHT 25
//ÕÏ°­Îï
#define BLOCK_HEIGHT 25
#define BLOCK_WIDTH 50


//½ÇÉ«
#define WALL_NUM 30
#define MAN_NUM 4
#define MAN_WIDTH 80
#define MAN_HEIGHT 150
#define MAN_XOFFSET WALL_WIDTH+BG_WIDTH/2-MAN_WIDTH/2
#define MAN_YOFFSET BG_HEIGHT-MAN_HEIGHT-50
#define MAN_CENTER BG_HEIGHT-MAN_HEIGHT*2
//Ö¸Õë
#define POINTER_WIDTH 60
#define POINTER_HEIGHT 60
#define POINTER_XOFFSET WALL_WIDTH+BG_WIDTH/2-POINTER_WIDTH/2
#define POINTER_YOFFSET MAN_YOFFSET-POINTER_HEIGHT